version: "3"

tasks:
    default:
        desc: List available tasks
        cmds:
            - task --list

    fmt:
        desc: Format Zig code using zig fmt
        cmds:
            - zig fmt src/

    test:
        desc: Run unit tests
        cmds:
            - zig build test

    run:
        desc: Run the 3270 emulator
        deps: [fmt, clean]
        cmds:
            - zig build run

    build:
        desc: Build the 3270 emulator
        cmds:
            - zig build

    check:
        desc: Format check and run tests (pre-commit validation)
        cmds:
            - zig fmt --check src/
            - zig build test

    clean:
        desc: Clean build artifacts and cache
        cmds:
            - rm -rf .zig-cache zig-out

    dev:
        desc: Development workflow - format, test, and build
        deps: [fmt, test, build]
        cmds:
            - echo "✓ Code formatted, tests passed, and built successfully"
