version: "3"

# Task runner for zig-3270 TN3270 terminal emulator
# Use: task [task-name] to run a task
# Use: task --list to see all available tasks

tasks:
    default:
        desc: List available tasks
        cmds:
            - task --list

    # === CODE QUALITY & TESTING ===

    loc:
        desc: Count lines of code using tokei
        cmds:
            - tokei src/ --files

    fmt:
        desc: Format Zig code using zig fmt
        cmds:
            - zig fmt src/

    test:
        desc: Run all tests (unit + integration + benchmarks)
        cmds:
            - zig build test

    test-unit:
        desc: Run unit tests only (fastest feedback)
        cmds:
            - echo "Running unit tests..."
            - zig build test 2>&1 | head -50

    test-integration:
        desc: Run integration tests (e2e workflows combining multiple modules)
        cmds:
            - 'echo "Running integration tests from integration_test.zig (7 tests)"'
            - task test

    test-benchmark:
        desc: Run performance benchmarks (parser, executor, field management)
        cmds:
            - 'echo "Running benchmarks from benchmark.zig (6 throughput tests)"'
            - task test

    check:
        desc: Format check and run tests (pre-commit validation)
        cmds:
            - zig fmt --check src/
            - zig build test

    dev:
        desc: Development workflow - format, test, and build
        deps: [fmt, test, build]
        cmds:
            - echo "✓ Code formatted, tests passed, and built successfully"

    # === BUILD & EXECUTION ===

    build:
        desc: Build the 3270 emulator
        cmds:
            - zig build

    clean:
        desc: Clean build artifacts and cache
        cmds:
            - rm -rf .zig-cache zig-out

    run:
        desc: Run the 3270 emulator
        deps: [fmt, clean]
        cmds:
            - zig build run

    # === INTEGRATION & EXAMPLES ===

    test-ghostty:
        desc: Visual test of libghostty-vt integration
        cmds:
            - zig build test-ghostty

    test-connection:
        desc: Test TN3270 connection to public mainframe (mvs38j.com:3270)
        cmds:
            - zig build test-connection

    test-connection-custom:
        desc: Test TN3270 connection to custom host (usage - task test-connection-custom -- host port)
        cmds:
            - zig build test-connection -- {{.CLI_ARGS}}

    mock-server:
        desc: Run mock 3270 server on localhost:3270 for testing
        cmds:
            - zig build
            - ./zig-out/bin/mock-server

    test-mock:
        desc: Test connection to local mock 3270 server (requires mock-server running in another terminal)
        cmds:
            - ./zig-out/bin/client-test 127.0.0.1 3270

    hex-viewer:
        desc: Run hex viewer example
        cmds:
            - zig build hex-viewer

    # === RELEASES ===

    release:
        desc: Create and push a release tag (usage - task release -- v0.2.0)
        cmds:
            - |
              TAG="{{.CLI_ARGS}}"
              if [ -z "$TAG" ]; then
                echo "Error: Tag required (usage: task release -- v0.2.0)"
                exit 1
              fi
              echo "Creating annotated tag: $TAG"
              git tag -a "$TAG" -m "Release $TAG"
              echo "Pushing tag to origin..."
              git push origin "$TAG"
              echo "✓ Released $TAG"
